###
POST http://localhost:9566/send/message/bmd579@gmail.com/bmd579@gmail.com
Content-Type: application/text

my message


###
POST http://192.168.10.179:9566/prepare/then/send/message/bmd579@gmail.com/mm7amini@gmail.com
Content-Type: application/text

my message