version: '3.7'
services:

  rabbitmq:
    build:
      context: .
      dockerfile: RabbitMQwithStompDockerfile
    ports:
      - "5672:5672"
      - "15672:15672"      
      - "4369:4369"            
      - "25672:25672"     
      - "61613:61613"
      - "61614:61614"

