GET http://localhost:9585/api/wonder
Accept: application/json

###
GET http://localhost:9585/api/like
Accept: application/json

###
GET http://localhost:9585/api/match
Accept: application/json

###
POST http://192.168.1.188:9531/v1/chat/tom/queues

###
POST http://localhost:9566/prepare/then/send/message/jlo/taylor?topic=messages
Content-Type: application/text

tom's message to taylor through messages


###
POST http://localhost:9566/prepare/then/send/message/jlo/taylor?topic="amp.topic"
Content-Type: application/text

tom's message to taylor through amq.topic