GET http://localhost:9585/api/wonder
Accept: application/json

###
GET http://localhost:9585/api/like
Accept: application/json

###
GET http://localhost:9585/api/match
Accept: application/json

###
POST http://192.168.10.179:9591/v1/chat/taylor/queues

###
POST http://localhost:9566/prepare/then/send/message/taylor/jlo?topic=messages
Content-Type: application/text

hi JLO

###
POST http://localhost:9591/v1/chat/messages
Content-Type: application/json

{
  "sender": "mm7amini@gmail.com",
  "receiver": "bmd579@gmail.com",
  "content": "hi kooni"
}

###
POST http://localhost:9591/v1/chat/queues/user/bmd579@gmail.com
