server.port: 9531

management:
  server.port: 9532
  health:
    defaults.enabled: true
    diskspace.enabled: false
  endpoints:
    web:
      base-path: /
      exposure.include: "*"
  endpoint:
    prometheus:
      enabled: true
    health:
      enabled: true
      show-details: never
    auditevents.enabled: false
  metrics:
    tags:
      application: ${spring.application.name}
      enable.jvm: true
      enable.jvm.gc.pause: true
      enable.jvm.memory: true
      enable.jvm.threads: true
      enable.process: true
      enable.process.files: true
      enable.http: true
      enable.http.server.requests: true
      enable.logback: true
      enable.system: true
    export:
      prometheus:
        enabled: true

spring:
  rsocket:
    server:
      port: 7000
      transport: websocket
#      mapping-path: /rsocket

  config:
    import: optional:consul:localhost:8500
  application:
    name: api-gateway
  kafka:
    bootstrap-servers: "localhost:9092"

  sleuth:
    sampler.probability: 1.0
    scheduled.skip-pattern: .*ConfigWatch|.*ConsulCatalogWatch|.*/api/v1/spans
  zipkin.base-url: http://system-zipkin/
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
        health-check-path: /health

kafka:
  topic:
    config:
      event: '3:2'

---
spring:
  config:
    activate:
      on-profile: local

kafka:
  topic:
    config:
      event: '1:1'

---
spring:
  config:
    activate:
      on-profile: no-consul
  application:
    name: api-gateway

kafka:
  topic:
    config:
      event: '1:1'
