server.port: 9591

management:
#  server.port: 9592
  health:
    defaults.enabled: true
    diskspace.enabled: false
  endpoints:
    web:
      base-path: /
      exposure.include: "*"
  endpoint:
    prometheus:
      enabled: true
    health:
      enabled: true
      show-details: never
    auditevents.enabled: false
  metrics:
    tags:
      application: ${spring.application.name}
      enable.jvm: true
      enable.jvm.gc.pause: true
      enable.jvm.memory: true
      enable.jvm.threads: true
      enable.process: true
      enable.process.files: true
      enable.http: true
      enable.http.server.requests: true
      enable.logback: true
      enable.system: true
    export:
      prometheus:
        enabled: true

spring:
  main:
    web-application-type: reactive
  rsocket:
    server:
      ssl:
        enabled: true
        key-store: "classpath:keystore.p12"
        key-store-password: ohpassword
        keyStoreType: PKCS12
        keyAlias: tomcat
      address: 0.0.0.0
      port: 8080
      transport: websocket

  config:
    import: optional:consul:localhost:8500
  application:
    name: api-gateway
  kafka:
    bootstrap-servers: "localhost:9092"
    producer:
      key-serializer: org.springframework.kafka.support.serializer.StringOrBytesSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  sleuth:
    sampler.probability: 1.0
    scheduled.skip-pattern: .*ConfigWatch|.*ConsulCatalogWatch|.*/api/v1/spans
  zipkin.base-url: http://system-zipkin/
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
    consul:
      discovery:
        prefer-ip-address: true
        health-check-path: /health

kafka:
  topic:
    config:
      event: '1:1'
      update: '1:1'

server:
    ssl:
      key-store: "classpath:keystore.p12"
      key-store-password: ohpassword
      keyStoreType: PKCS12
      keyAlias: tomcat

---
spring:
  config:
    activate:
      on-profile: local

  kafka:
    bootstrap-servers: "localhost:29092"

---
spring:
  config:
    activate:
      on-profile: confluent

  kafka:
    bootstrap-servers: "pkc-l7q2j.europe-north1.gcp.confluent.cloud:9092"
    properties:
      sasl:
        mechanism: PLAIN
        jaas.config: "org.apache.kafka.common.security.plain.PlainLoginModule   required username='5WDGJP7DLN5VO2SQ'   password='3iRgkgd3EP4mO1ZnLbaE8F85W68spkQPrvsvf4w8ubTnRkr8r9bgNlXrcRnHcgdZ';"
      security.protocol: SASL_SSL
      session.timeout.ms: 45000
      basic:
        auth:
          credentials:
            source: USER_INFO
          user.info: "5WDGJP7DLN5VO2SQ:3iRgkgd3EP4mO1ZnLbaE8F85W68spkQPrvsvf4w8ubTnRkr8r9bgNlXrcRnHcgdZ"

kafka:
  topic:
    config:
      event: '6:3'
      update: '6:3'

---
spring:
  config:
    activate:
      on-profile: no-consul
  application:
    name: api-gateway

