name: dart_game_engine
description: A server app using the shelf package and Docker.
version: 1.0.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  args: ^2.3.2
  dart_amqp: ^0.2.4
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  meta: ^1.8.0
  equatable: ^2.0.5
  forge2d: ^0.11.0

dev_dependencies:
  http: ^0.13.5
  lints: ^2.0.1
  test: ^1.22.2

