server.port: 80

management:
  server.port: 9569
  health:
    defaults.enabled: true
    diskspace.enabled: false
  endpoints:
    web:
      base-path: /
      exposure.include: "*"
  endpoint:
    prometheus:
      enabled: true
    health:
      enabled: true
      show-details: never
    auditevents.enabled: false
  metrics:
    tags:
      application: ${spring.application.name}
      enable.jvm: true
      enable.jvm.gc.pause: true
      enable.jvm.memory: true
      enable.jvm.threads: true
      enable.process: true
      enable.process.files: true
      enable.http: true
      enable.http.server.requests: true
      enable.logback: true
      enable.system: true
  prometheus:
    metrics:
      export:
        enabled: true


spring:
  config:
    import: optional:consul:localhost:8500
  application:
    name: webauthn-server
  kafka:
    streams:
      replication-factor: 1
      properties:
        num.stream.threads: 1
    bootstrap-servers: "localhost:9092"

  sleuth:
    sampler.probability: 1.0
    scheduled.skip-pattern: .*ConfigWatch|.*ConsulCatalogWatch|.*/api/v1/spans
  zipkin.base-url: http://system-zipkin/
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
        health-check-path: /health

---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    bootstrap-servers: "localhost:29092"
    streams:
      replication-factor: 1
---
spring:
  config:
    activate:
      on-profile: no-consul
  application:
    name: webauthn-server
