package io.github.pubsubseekbucket.publish.persisted;

import com.google.pubsub.v1.PubsubMessage;
import lombok.extern.slf4j.Slf4j;

import java.util.Collection;
import java.util.function.Function;

/**
 * This event publisher offers guaranteed at-least-once delivery once the transaction scope of the {@link #persist(Object)} has been committed
 * (if present, may be omitted if not required). Compared to the {@link PersistedPublisher}, {@link OutboxPublisher} frees the caller from keeping track of {@link PublishTrigger} instances.
 * <p>
 * Use the {@link io.github.pubsubseekbucket.publish.PublisherFactory} class to create OutboxPublisher instances.
 * <p>
 * The caller is responsible for ensuring the correct sequence of related state changes prior to committing the related transaction scope.
 * See {@link org.springframework.transaction.annotation.Propagation#SUPPORTS} usage in {@link PostgresOutboxDao}.
 * <p>
 * The OutboxPublisher keeps track of the {@link PublishTrigger} instances generated by persist() calls.
 * Once the transaction scope is completed, the caller should invoke the {@link PublishTriggerRepository#publish()} method to ensure a timely delivery.
 * <p>
 * This implementation will persist the full outgoing PubSub messages, to ensure that any provided header is retained on re-transmission.
 * <p>
 * Note: If the destination of this publisher is a PubSub topic with schema validation enabled, there is no means to drop
 * non-conformal messages from the Outbox in this implementation. Consider using/adding a custom Drainer in that case with
 * DLQ handling of stuck messages.
 *
 * @param <T> Event type of this publisher, corresponding to the underlying PubSub topic spec.
 */
@Slf4j
public class OutboxPublisher<T> {

    private final PublishTriggerRepository publishTriggerRepository;
    private final PersistedPublisher<T> persistedPublisher;

    OutboxPublisher(
            PersistedPublisher<T> persistedPublisher,
            PublishTriggerRepository publishTriggerRepository
    ) {
        this.persistedPublisher = persistedPublisher;
        this.publishTriggerRepository = publishTriggerRepository;
    }

    /**
     * Write a single outgoing event to the persisted outbox and register a publish trigger
     *
     * @param event The PubSub message payload
     * @throws FailedToPersistException if the event cannot be added to the outbox
     */
    public void persist(T event) throws FailedToPersistException {
        publishTriggerRepository.add(persistedPublisher.persistEvent(event, PubsubMessage.newBuilder()));
    }

    /**
     * Write a collection of outgoing events to the persisted outbox as a batch and register publish triggers
     *
     * @param events the payloads to send as individual PubSub messages
     * @throws FailedToPersistException if the event cannot be added to the outbox
     */
    public void persist(Collection<T> events) throws FailedToPersistException {
        publishTriggerRepository.add(persistedPublisher.persistEvents(events, e -> PubsubMessage.newBuilder()));
    }

    /**
     * Write a single outgoing event to the persisted outbox together with a PubSub message builder for any custom headers that should be included. Register a publish trigger.
     *
     * @param event   the message payload to include in the PubSub message
     * @param builder a PubSub message builder for custom headers
     * @throws FailedToPersistException if the event cannot be added to the outbox
     */
    public void persist(T event, PubsubMessage.Builder builder) throws FailedToPersistException {
        publishTriggerRepository.add(persistedPublisher.persistEvent(event, builder));
    }

    /**
     * Write a collection of events to the persisted outbox as a batch, using the provided PubSub message builder function to construct the actual messages. Register publish triggers.
     *
     * @param events          the payloads to send as individual PubSub messages
     * @param builderFunction a function to create a custom PubSub message builder for each outgoing event
     * @throws FailedToPersistException if the events cannot be added to the outbox
     */
    public void persist(Collection<T> events, Function<T, PubsubMessage.Builder> builderFunction) throws FailedToPersistException {
        publishTriggerRepository.add(persistedPublisher.persistEvents(events, builderFunction));
    }
}
