version: '3.7'
services:

  neo4j:
    image: neo4j:3.5.11
    hostname: neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
      - "6477:6477"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/plugins:/plugins
      - ./neo4j/import:/var/lib/neo4j/import    
    environment:
      - NEO4J_AUTH=neo4j/test
      - NEO4JLABS_PLUGINS=["apoc", "graph-algorithms"]
      - NEO4J_dbms_connector_http_listen__address= :7474
      - NEO4J_dbms_connector_https_listen__address= :6477
      - NEO4J_dbms_connector_bolt_listen__address= :7687
      - NEO4J_dbms_logs_debug_level=DEBUG
      - NEO4J_apoc_import_file_enabled="true"
#      - NEO4J_HEAP_MEMORY=1G
#      - NEO4J_CACHE_MEMORY=1G
      - NEO4J_dbms_security_procedures_whitelist= apoc.*, algo.*
      - NEO4J_dbms_security_procedures_unrestricted= apoc.*,algo.*
#      NEO4J_AUTH: none

