version: "3.7"
services:

  consul:
    container_name: consul
    hostname: consul
    image: consul
    ports:
      - "8500:8500"
      - "8300:8300"
    volumes:
      - ./metrics/consul.json:/consul/config/consul.json

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
#    network_mode: host
    user: "1000"
    volumes:
      - ./metrics/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./metrics/prometheus_db:/var/lib/prometheus
      - ./metrics/prometheus_db:/prometheus
      - ./metrics/prometheus_db:/etc/prometheus
      - ./metrics/alert.rules:/etc/prometheus/alert.rules
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.route-prefix=/'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    ports:
      - '9090:9090'

#  grafana:
#    container_name: grafana
#    image: grafana/grafana
##    network_mode: host
#    user: "1000"
#    environment:
#      - GF_SECURITY_ADMIN_USER=admin
#      - GF_SECURITY_ADMIN_PASSWORD=admin
#    volumes:
#      - ./metrics/grafana_db:/var/lib/grafana
#    depends_on:
#      - prometheus
#    ports:
#      - '3000:3000'

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    build:
      context: ./rabbitmq
      dockerfile: RabbitMQwithStompDockerfile
    ports:
      - "5672:5672"
      - "15672:15672"
      - "4369:4369"
      - "25672:25672"
      - "61613:61613"
      - "61614:61614"
    environment:
      SERVICE_IGNORE: any_value

  api-gateway:
    container_name: api-gateway
    hostname: api-gateway
    image: bmd007/api-gateway
    ports:
      - "9532:9532"
      - "9533:9533"
    depends_on:
      - consul
      - prometheus
    environment:
      SPRING_PROFILES_ACTIVE: confluent
      SPRING_CLOUD_CONSUL_HOST: consul

  message-publisher:
    container_name: message-publisher
    hostname: message-publisher
    image: bmd007/wonder-matcher
    ports:
      - "9566:9566"
      - "9567:9567"
    depends_on:
      - api-gateway
      - consul
      - prometheus
    environment:
      SERVER_PORT: 9566
      MANAGEMENT_SERVER_PORT: 9567
      SPRING_PROFILES_ACTIVE: confluent
      SPRING_CLOUD_CONSUL_HOST: consul

  wonder-matcher:
    container_name: wonder-matcher
    hostname: wonder-matcher
    image: bmd007/wonder-matcher
    ports:
      - "9585:9585"
      - "9586:9586"
      - "8084:8084"
      - "9097:9097"
    depends_on:
      - api-gateway
      - consul
      - prometheus
    environment:
      KAFKA_STREAMS_SERVER_CONFIG_APP_IP: wonder-matcher
      KAFKA_STREAMS_SERVER_CONFIG_APP_PORT: 9585
      SPRING_PROFILES_ACTIVE: confluent
      SPRING_CLOUD_CONSUL_HOST: consul
