server:
  port: 7461

spring:
  cloud:
    service-registry.auto-registration.enabled: true
    loadbalancer:
      ribbon:
        enabled: false

---
spring:
  profiles: nomad

---
spring:
  profiles:
    - docker_compose
