server.port: 9598

management:
  server.port: 9599
  health:
    defaults.enabled: true
    diskspace.enabled: false
  endpoints:
    web:
      base-path: /
      exposure.include: "*"
  endpoint:
    prometheus:
      enabled: true
    health:
      enabled: true
      show-details: never
    auditevents.enabled: false
  metrics:
    tags:
      application: ${spring.application.name}
      enable.jvm: true
      enable.jvm.gc.pause: true
      enable.jvm.memory: true
      enable.jvm.threads: true
      enable.process: true
      enable.process.files: true
      enable.http: true
      enable.http.server.requests: true
      enable.logback: true
      enable.system: true
  prometheus:
    metrics:
      export:
        enabled: true

spring:
  application:
    name: game-engine
  config:
    import: optional:consul:localhost:8500
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
        health-check-path: /health
  kafka:

    bootstrap-servers: "localhost:9092"
    producer:
      retries: 3
      acks: all
      key-serializer: org.springframework.kafka.support.serializer.StringOrBytesSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: earliest

  rabbitmq:
    username: imarabbit
    password: noyouarenot
    host: localhost
    port: 5672

kafka:
  topic:
    config:
      event: '1:1'
      changelog: '1:1'
---
spring:
  config:
    activate:
      on-profile: local

  kafka:
    bootstrap-servers: "localhost:29092"
---
spring:
  config:
    activate:
      on-profile: no-consul
  application:
    name: message-publisher
