name: dance_partner_finder
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^3.0.0
  cupertino_icons: ^1.0.5
  mocktail: ^0.3.0
  bloc: ^8.1.0
  equatable: ^2.0.5
  bloc_test: ^9.1.0
  flutter_bloc: ^8.1.1
  rx_bloc: ^4.0.0
  rxdart: ^0.27.7
  location: ^4.4.0
  http: ^0.13.5
  dio: ^5.1.0
  web_socket_channel: ^2.3.0
  universal_io: ^2.0.4
  stomp_dart_client: ^0.4.4
  rsocket:
    git:
      url: git@github.com:rsocket/rsocket-dart.git
      ref: master
  firebase_auth: ^4.2.5
  google_sign_in: ^6.0.0
  google_fonts: ^4.0.0
  font_awesome_flutter: ^10.3.0
  firebase_core: ^2.4.1
  firebase_storage: ^11.0.10
  firebase_app_check: ^0.1.1+8
  file_picker: ^5.2.5
  flutter_webrtc: ^0.9.19
  sdp_transform: ^0.3.2
  flutter_svg: ^2.0.0
  flame: ^1.6.0
  flame_forge2d: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/images/red_girl/
     - assets/images/green_girl/
     - assets/images/svg/
     - assets/images/TeamGunner/CHARACTER_SPRITES/Green/
     - assets/images/TeamGunner/EXTRAS/
     - assets/images/Tiles/
     - assets/images/Objects/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
