name: Flutter build for firebase

on:
  push:
    branches: [ ignore-me-for-now ]
    paths:
        - 'dance_partner_finder/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
   
    steps:
      - uses: actions/checkout@v4

#      - uses: subosito/flutter-action@v2
#        with:
#          flutter-version: '3.3.10'
#          channel: 'stable'
#
#      - name: flutter version
#        run: flutter --version
#
#      - name: flutter doctor
#        run: flutter doctor
#
#      - name: flutter pub get
#        working-directory: ./dance_partner_finder
#        run: flutter pub get
#
#      - name: flutter build web
#        working-directory: ./dance_partner_finder
#        run: flutter build web --release
#
#      - name: copy from flutter build to firebase folder
#        run: |
#          cp -r ./dance_partner_finder/build/web/* ./deployment/gcp/firebase/flutter_ui/public/
#          ls ./deployment/gcp/firebase/flutter_ui/public/
#
#      - name: Deploy to firebase
#        uses: FirebaseExtended/action-hosting-deploy@v0
#        with:
#          repoToken: '${{ secrets.GITHUB_TOKEN }}'
#          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_WONDERLAND_007 }}'
#          projectId: wonderland-007
#          entryPoint: ./deployment/gcp/firebase/flutter_ui
#          channelId: live
