name: Flutter CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.10'
          channel: 'stable'

      - name: flutter version
        run: flutter --version

      - name: flutter pub get
        working-directory: ./dance_partner_finder
        run: flutter pub get

      - name: flutter build web
        working-directory: ./dance_partner_finder
        run: flutter build web --release

      - name: copy from flutter build to firebase folder
        run: |
          cp -r ./dance_partner_finder/build/web/* ./deployment/gcp/firebase/flutter_ui/public/ 
          ls ./deployment/gcp/firebase/flutter_ui/public/ 

      - name: create PR for the built flutter web
        uses: peter-evans/create-pull-request@v4
        add-paths: ./deployment/gcp/firebase/flutter_ui/public/
        commit-message: creating PR for deploying flutter to firebase

