name: Flutter CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: flutter pub get
        working-directory: ./dance_partner_finder
        run: flutter pub get

#      - run: flutter test

      - name: flutter build web
        working-directory: ./dance_partner_finder
        run: flutter build web --release

      - name: Upload Web Build Files
        working-directory: ./dance_partner_finder
        uses: actions/upload-artifact@v2
        with:
            name: web-release
            path: ./build/web/

  deploy:
    name: Deploy Web Build
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Web Release
        uses: actions/download-artifact@v2
        with:
          name: web-release

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./

